### ISSUE TITLE
os.path.dirname does not work with path like objects in Python 3.5

### ISSUE THREAD

**Issue by nizar-m** [nizar-m/tox-local-hooks#2]
While finding out the directory of the tox config file, this throws the following error
   
     AttributeError: 'LocalPath' object has no attribute 'rfind'
